name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

# Даём права на запись
permissions:
  contents: write   # разрешаем пушить коммиты
  pages: write      # нужно для деплоя на Pages (если используется pages-action)
  id-token: write   # может понадобиться для OIDC-авторизации (необязательно)


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist 
